config/routes.rb
Rails.application.routes.draw do
  resources :file_uploads
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'file_uploads#new'
end

app/models/file_upload.rb
class FileUpload < ApplicationRecord
  has_many_attached :files
  validates :name, presence: true
  validate :file_attached

def save
  super
  rescue ActiveRecord::RecordNotUnique => err
    errors.add(:files, "'#{files.filename}' already exists")
    false
end

  private

  def file_attached
    if files.attached? == false
      files.purge_later
      errors[:base] << 'File is not attached'
    elsif files.attached?
      files.each do |file|
        if file.byte_size > 10485760
          file.purge
          errors[:base] << 'File is too large. It has to be below 10MB'
        end
      end
    end
  end
end

app/controllers/file_uploads_controller.rb
class FileUploadsController < ApplicationController
  before_action :set_file_upload, only: [:show, :edit, :update, :destroy]

  # GET /file_uploads
  # GET /file_uploads.json
  def index
    @file_uploads = FileUpload.with_attached_files
  end

  # GET /file_uploads/1
  # GET /file_uploads/1.json
  def show
  end

  # GET /file_uploads/new
  def new
    @file_upload = FileUpload.new
  end

  # GET /file_uploads/1/edit
  def edit
  end

  # POST /file_uploads
  # POST /file_uploads.json
  def create
    @file_upload = FileUpload.new(file_upload_params)

    respond_to do |format|
      if @file_upload.save
        format.html { redirect_to @file_upload, notice: 'File upload was successfully created.' }
        format.json { render :show, status: :created, location: @file_upload }
      else
        @file_upload.files.purge_later
        format.html { render :new }
        format.json { render json: @file_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /file_uploads/1
  # PATCH/PUT /file_uploads/1.json
  def update
    respond_to do |format|
      if @file_upload.update(file_upload_params)
        format.html { redirect_to @file_upload, notice: 'File upload was successfully updated.' }
        format.json { render :show, status: :ok, location: @file_upload }
      else
        @file_upload.files.purge_later
        format.html { render :edit }
        format.json { render json: @file_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /file_uploads/1
  # DELETE /file_uploads/1.json
  def destroy
    @file_upload.destroy
    @file_upload.files.purge_later
    respond_to do |format|
      format.html { redirect_to file_uploads_url, notice: 'File upload was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_file_upload
      @file_upload = FileUpload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def file_upload_params

      params.require(:file_upload).permit(:name, files: []) if params[:file_upload]
    end
end

app/helpers/file_uploads_helper.rb
module FileUploadsHelper
end

app/views/file_uploads/_form.html.erb
<%= form_with(model: file_upload, local: true) do |form| %>
  <% if file_upload.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <% file_upload.errors.full_messages.each do |message| %>
        <span><%= message %></span><br>
      <% end %>
    </div>
  <% end %>
  <div class="alert alert-danger duplicate-message-container" role="alert">
    <span id="duplicate_message"></span>
  </div>

  <div id="progress-bar"></div>
  <div class="form-group text-center">
    <%= form.text_field :name, class: "form-control file-name text-center", placeholder: 'Enter a file name' %>
    <small id="emailHelp" class="form-text text-muted">Kindly enter a file name for your uploads</small>
  </div>

  <div class="upload-btn-wrapper">
    <div>
      <%= image_tag("cloud.svg", class: "cloud-upload-icon") %>
    </div>
    <span>Drag files here or </span><span class="browse"> &nbsp; browse</span>
    <%= form.file_field :files, multiple: true, direct_upload: true , class: "dropzone" %>
  </div>

  <div class="form-group actions">
    <%= form.submit 'UPLOAD FILE', :class => 'btn btn-primary btn-upload', :id=> 'upload-file', data: { disable_with: false } %>
  </div>
<% end %>

app/views/file_uploads/edit.html.erb
<div class="all-uploads">
  <div class="file-container">
    <div class="box">
      <div class="header-container">
        <p class="header-title">EDIT FILE UPLOAD</p>
      </div>
      <%= render 'form', file_upload: @file_upload %>

      <%= link_to 'SHOW', @file_upload, :class => 'small list-uploads' %> |
      <%= link_to 'BACK', file_uploads_path, :class => 'small list-uploads' %>
    </div>
  </div>
</div>

app/views/file_uploads/index.html.erb
<div class="container">
  <br><br>
  <div class="row">
    <div class="col-md-8">
      <p class="file-upload-title">FILE UPLOADS</p>
    </div>
    <div class="col-md-4 justify-content-end">
      <%= link_to 'NEW FILE UPLOAD', new_file_upload_path, :class => 'btn btn-primary file-upload'  %>
    </div>
  </div>

  <% if @file_uploads.count > 0 %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">File Name</th>
        <th scope="col">Show files</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @file_uploads.each do |file_upload| %>
        <tr>
          <td><%= file_upload.name %></td>
          <td><%= link_to file_upload, class: 'show-link' do %>
            <i class="fa fa-file"></i>
            <span class="small">show file</span>
            <% end %>
          </td>
          <td>
            <span class="edit-icon">
              <%= link_to edit_file_upload_path(file_upload), class: 'edit-link' do %>
                <i class="fa fa-edit"></i>
              <% end %>
            </span>
            <span>
              <%= link_to file_upload, method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete-link' do %>
                <i class="fa fa-trash"></i>
              <% end %>
            </span>
          </td>
        </tr>
      <% end %>
      <% else %>
      <div class="no-record-container">
        <p class="text-center no-record"> No file uploaded :( </p>
      </div>
      <% end %>
    </tbody>
  </table>
  <br>
</div>

app/views/file_uploads/new.html.erb
<div class="all-uploads">
    <div class="file-container">
      <div class="box">
        <div class="header-container">
          <p class="header-title">UPLOAD FILES</p>
        </div>
        <%= render 'form', file_upload: @file_upload %>

        <%= link_to 'SHOW ALL UPLOADS', file_uploads_path, :class => 'small list-uploads' %>
      </div>
    </div>
  </div>

app/views/file_uploads/show.html.erb
<div class="container">
  <br><br>
  <div class="row">
    <div class="col-md-8">
      <p class="attachment-title"><%= @file_upload.name %><span> Attachments</span></p>
    </div>
    <div class="col-md-4 order-12">
      <%= link_to 'EDIT', edit_file_upload_path(@file_upload), :class => 'btn btn-danger btn-sm' %>
      <%= link_to 'BACK TO UPLOADS', file_uploads_path, :class => 'btn btn-success btn-sm'%>
    </div>
  </div>
  <div class="row">
    <% if @file_upload.files.attached? %>
    <!-- @post.image.present? will always return true, use attached? to check presence -->
    <% @file_upload.files.each do |file| %>
      <div class="col-md-4 attachment">
        <div class="attachment-box">
          <%if file.content_type.start_with? 'image/' %>
            <%= image_tag(file, class: "attachment-image") %>
          <% else %>
            <%= image_tag("file.png", class: "attachment-image") %>
          <% end %>
        <div class="text-center download-btn"><%= link_to 'Download', file, download: '', :class => 'btn btn-primary btn-sm download'  %></div>
      </div>
    </div>
    <% end %>
    <% else %>
      <div class="no-record-container">
        <p class="text-center no-record"> No attachment for this file :( </p>
      </div>

    <% end %>
  </div>
</div>